# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Eliza Weisman"

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "Statement"
    href:           "/about"
  - name:           "Résumé & CV"
    href:           "/assets/cv/cv-art.pdf"
  - name:           "Contact"
    href:           "mailto://hi@hawkweisman.me"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

excerpt_separator: "<!--excerpt-->"
